version: '3.8'
services:
  webapp: 
    build:
      context: .
      args:
        - PORT=${PORTEXPOSED}
    ports:
      - '${PORTEXPOSED}:${PORTEXPOSED}'
    restart: always
    container_name: fletappcontainer
    image: webapp/fletapp:latest
